### ISSUE TITLE
CDN scoicon_css 默认提供的 min.css 文件访问不了

### ISSUE THREAD

**Issue by Chocolate1999** [valor-x/hexo-theme-solitude#144]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://docs.wzsco.top/FAQ.html)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

MacOS

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

很感谢作者的开发！有个小问题，我是用 npm 安装的，理论上 git clone 也会有问题：

CDN scoicon_css 默认提供的 min.css 文件访问不了

```
CDN:
    option:
        scoicon_css: https://cdn.cbd.int/solitude-source/icon/scoicon.min.css
```

我后面是看了 [demo](https://github.com/valor-x/solitude-demo.efu.me/blob/main/_config.solitude.yml) 配置，暂时用的这个：

```
https://cdn2.codesign.qq.com/icons/7pOrz0WXB5ZWJPX/latest/iconfont.css
```

### 终端日志 📒

<此处粘贴终端日志>

**Comment by efuo** [comment]
理论上可以的，demo的配置换成了 design 的，只适用于国内

**Comment by Chocolate1999** [comment]
我是 cdn.cbd.int 这个域名下的目前 cdn 链接打不开，换了海外节点也打不开 universe.min.js 与 waterfall.min.js 这些访问不了

**Comment by efuo** [comment]
> 我目前是 cdn.cbd.int 这个域名下的 cdn 链接打不开，换了海外节点也打不开 universe.min.js 与 waterfall.min.js 这些访问不了

能发一下你的站吗

**Comment by efuo** [comment]
<img width="2524" alt="image" src="https://github.com/valor-x/hexo-theme-solitude/assets/74389842/6fc4e636-6f74-488b-94a9-40666ca224e2">

https://cdn.cbd.int/solitude-source/icon/scoicon.min.css
会自动识别版本号

npm仓库：https://www.npmjs.com/package/solitude-source

**Comment by efuo** [comment]
> 我目前是 cdn.cbd.int 这个域名下的 cdn 链接打不开，换了海外节点也打不开 universe.min.js 与 waterfall.min.js 这些访问不了

可能是地区屏蔽了，谢谢提醒，会在文档补充

**Comment by efuo** [comment]
有需要可以加群，群里人多回复快

**Comment by isYangs** [comment]
> 我目前是 cdn.cbd.int 这个域名下的 cdn 链接打不开，换了海外节点也打不开 universe.min.js 与 waterfall.min.js 这些访问不了

经过 Ping 发现 cdn.cbd.int 确实在一些地区可能访问比较慢或者打不开，但是你可以尝试是用 unpkg、jsdelivr 或者其他可以搜索到 solitude-source 这个 npm 包的 CDN 来替换即可。

例如：

[https://unpkg.com/solitude-source@1.0.5/icon/scoicon.min.css](https://unpkg.com/solitude-source@1.0.5/icon/scoicon.min.css)

[https://cdn.jsdelivr.net/npm/solitude-source@1.0.5/icon/scoicon.min.css](https://cdn.jsdelivr.net/npm/solitude-source@1.0.5/icon/scoicon.min.css)
