### ISSUE TITLE
无高亮

### ISSUE THREAD

**Issue by btwoa** [valor-x/hexo-theme-solitude#147]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://docs.wzsco.top/FAQ.html)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

开发板 (dev)

### 问题描述 😯

代码块无高亮，hightlight启用失败

### 终端日志 📒

<此处粘贴终端日志>

**Comment by efuo** [comment]
问题描述不清晰，重新补充
