### ISSUE TITLE
内容超宽时移动端样式错误

### ISSUE THREAD

**Issue by 828767** [valor-x/hexo-theme-solitude#161]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://docs.wzsco.top/FAQ.html)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

solitude version: `1.5.3`
当页面内容「已知链接标签或表格内容，code块未测」超宽时：
1.  链接标签内如渲染的链接卡片内容溢出页面框，**建议能让内容换行调整高度容纳下来**
    ![image](https://github.com/valor-x/hexo-theme-solitude/assets/57104623/8474a601-2ba1-43f2-bd8f-cf8655828b71)

2. 内容超宽页面在移动端展示时将造成页面样式错误
    ![image](https://github.com/valor-x/hexo-theme-solitude/assets/57104623/839e13c7-9b02-4430-9f3c-aba27b013681)
    或者有时候页面被顶到内容结束位置
    ![image](https://github.com/valor-x/hexo-theme-solitude/assets/57104623/5bd8d6ad-7267-4653-80eb-2f3cf34dc6d7)

### 终端日志 📒

<此处粘贴终端日志>

**Comment by efuo** [comment]
https://github.com/valor-x/hexo-theme-solitude/commit/1691978604cec81061a1c8dd9c1c7ec7c9d4ac04#diff-e6a9197279db062477cf2b47c656073482c0b9df89e91f227417bb87421d1ef1
