### ISSUE TITLE
[想法]: 建议统一{% link %} 标签语法格式

### ISSUE THREAD

**Issue by 828767** [valor-x/hexo-theme-solitude#162]
### 功能简介

统一{% link %} 标签语法格式

### 问题描述

[solitude](https://github.com/valor-x/hexo-theme-solitude) 中 `link.js` 直接默认的空格分割，而`image`，`btn`等标签语法标签语法格式都是用 `,` 分割各参数，稍不注意就会出现多个 `,` 造成内容错误，建议能统一，也方便内容通用。

> 当前solitude中链接标签自动获取 `favicon.png` 方式也有局限性，有些网站是 `ico` 或 `jpg` 等

### 实现效果

`{% link “标题”,  “描述”, "链接", "[显示图标]" %}`

### 你想到的可行的替代方案

暂时抄了隔壁anz....的 `link.js`

**Comment by efuo** [comment]
> ### 功能简介
> 统一{% link %} 标签语法格式
> 
> ### 问题描述
> [solitude](https://github.com/valor-x/hexo-theme-solitude) 中 `link.js` 直接默认的空格分割，而`image`，`btn`等标签语法标签语法格式都是用 `,` 分割各参数，稍不注意就会出现多个 `,` 造成内容错误，建议能统一，也方便内容通用。
> 
> > 当前solitude中链接标签自动获取 `favicon.png` 方式也有局限性，有些网站是 `ico` 或 `jpg` 等
> 
> ### 实现效果
> `{% link “标题”, “描述”, "链接", "[显示图标]" %}`
> 
> ### 你想到的可行的替代方案
> 暂时抄了隔壁anz....的 `link.js`
> 
> ### 其他内容
> _No response_

目前正在逐步调整，tags plugin 需要单独分离出来作为插件， #154

**Comment by efuo** [comment]
如果有想法可以参与进来
