### ISSUE TITLE
[想法]: 在文章中实现插入多张并排的图片的图库功能

### ISSUE THREAD

**Issue by hulebaji** [valor-x/hexo-theme-solitude#164]
### 功能简介

在文章中实现插入多张并排的图片的图库功能

### 问题描述

写文章过程中插入多张图片，有时候由于图片较多显得文章冗长，所以希望能支持类似与butterfly中的图库功能

### 实现效果

![image](https://github.com/valor-x/hexo-theme-solitude/assets/62818915/21205c51-634b-442c-a0d2-fefdf6c04c67)
![image](https://github.com/valor-x/hexo-theme-solitude/assets/62818915/10a973fd-3bbd-41bb-aa55-ed775515b38f)

### 你想到的可行的替代方案

https://butterfly.js.org/posts/dc584b87/#%E5%9C%96%E5%BA%AB
butterfly中的效果
![image](https://github.com/valor-x/hexo-theme-solitude/assets/62818915/52897d72-437e-4d9d-bbca-23317b16a44e)

### 其他内容

我从安知鱼主题中迁移时遇到的问题
![image](https://github.com/valor-x/hexo-theme-solitude/assets/62818915/808d8486-9d8b-4e23-abc1-60a9bd992913)
我不确定是暂时还没有支持这个功能还是我的书写格式出现了问题，希望大佬解决

**Comment by efuo** [comment]
此功能butterfly用了一个第三方库

**Comment by efuo** [comment]
pass 掉了，有个代替的解决方案，效果是这样的
<img width="768" alt="image" src="https://github.com/valor-x/hexo-theme-solitude/assets/74389842/47857c9c-15b1-4d84-8f6f-bbef5f9e5022">

**Comment by efuo** [comment]
已添加，不支持远程，仅支持本地
