### ISSUE TITLE
[Bug]: Twikoo评论模块设置问题

### ISSUE THREAD

**Issue by MGHYGitHub** [valor-x/hexo-theme-solitude#188]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

Twikoo评论部署后有界面错位问题,求适配
评论设置只有这一点地方,希望适配自适应界面设置
![PixPin_2024-03-28_22-30-50](https://github.com/valor-x/hexo-theme-solitude/assets/113328471/65aa0d9a-f24b-4d50-b422-65178d846dae)

**Comment by efuo** [comment]
修复了 https://github.com/valor-x/hexo-theme-solitude/commit/2b00bd7d91c463bdaa322d353b12969df41915b9#diff-e74b7769b302f63cfb3be2a36a35813ac6a5677a4d2eb51e9e64bd36a1942e72
