### ISSUE TITLE
[Bug]: 文章摘要AI异常

### ISSUE THREAD

**Issue by NiYa-Q** [valor-x/hexo-theme-solitude#192]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Mac/Linux

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

文章摘要异常，貌似缺少css：
<img width="1101" alt="image" src="https://github.com/valor-x/hexo-theme-solitude/assets/56643217/61ba10b3-f053-4661-b221-dddb3c3a7eae">

线上地址：https://blog.qjqq.cn/posts/a504.html

### 终端日志 📒

🈚️

**Comment by efuo** [comment]
<img width="1099" alt="image" src="https://github.com/valor-x/hexo-theme-solitude/assets/74389842/27d441f3-241e-4638-b72e-d92d0102c5d1">
