### ISSUE TITLE
[Bug]: 文章摘要AI 异常

### ISSUE THREAD

**Issue by NiYa-Q** [valor-x/hexo-theme-solitude#201]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Mac/Linux

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

祝问题是：概率性打开文章ai摘要没有任何输出，刷新一下就会正常。

**Comment by efuo** [comment]
什么

**Comment by NiYa-Q** [comment]
就是打开文章 摘要没有任何输出，需要刷新才会正常输出内容

**Comment by efuo** [comment]
好

**Comment by efuo** [comment]
试试
