### ISSUE TITLE
[Feature]: 接入 qexo 友链系统

### ISSUE THREAD

**Issue by Alcexn** [valor-x/hexo-theme-solitude#206]
### 功能简介

Qexo 友链系统

### 问题描述

建议，增加本地 Qexo 友链系统，提供两种友链(本地和 Qexo， 文档 https://www.oplog.cn/qexo/exts/flinks.html 可以通过 Qexo 新增友链 希望作者能够适配一下主题

### 实现效果

通过 Qexo 远程编辑友链

### 其他内容

Qexo 文档  https://www.oplog.cn/qexo/exts/flinks.html

**Comment by efuo** [comment]
这个需求太小，且是第三方的

**Comment by efuo** [comment]
完全使用qexo的数据，你只需要自己写样式就好了
