### ISSUE TITLE
[Bug]: 最后更新不显示时间

### ISSUE THREAD

**Issue by Alcexn** [valor-x/hexo-theme-solitude#207]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

![image](https://github.com/valor-x/hexo-theme-solitude/assets/125755021/b9d949d1-99ae-40e2-8cad-31363ba957f2)
最后更新时间不显示，尝试过删除缓存，网站链接https://blog.alcex.cn/ 

### 终端日志 📒

无报错

**Comment by efuo** [comment]
更新出现的bug，暂时别开，下个版本更新
