### ISSUE TITLE
[Bug]: 多张并排的图片的图库功能，但是我的图片是一个竖列下来的形式

### ISSUE THREAD

**Issue by hulebaji** [valor-x/hexo-theme-solitude#209]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

![2c3d168ab5a47abe8fd57a327c183a3f](https://github.com/valor-x/hexo-theme-solitude/assets/62818915/81fc1b35-7d96-4fb7-9402-bf128451cb49)
![ff049beedecd24362a2d9b45b089efd8](https://github.com/valor-x/hexo-theme-solitude/assets/62818915/6e2540bc-0bb3-430c-b398-a51c3499eb0b)
![5c3a7fbd8a4c9bf0d1ef22687dac790a_720](https://github.com/valor-x/hexo-theme-solitude/assets/62818915/d093c82f-d8e5-42ad-9b2a-6f1c0fd54015)
参照以上文档，但是我的图片是一个竖列下来的形式

### 终端日志 📒

Uncaught TypeError: waterfall is not a function
    at main.js?v=1.7.9:336:17
2main.js?v=1.7.9:336 Uncaught TypeError: waterfall is not a function
    at main.js?v=1.7.9:336:17

**Comment by efuo** [comment]
已修复

**Comment by hulebaji** [comment]
![image](https://github.com/valor-x/hexo-theme-solitude/assets/62818915/bb1e39ba-a46a-47f9-9023-b39c3d4e50ff)
出现多组图片的时候第二组图片还是会变成竖列下来的形式，但是这回F12没有报错

**Comment by efuo** [comment]
wow
等下，我等会再交一个

**Comment by efuo** [comment]
好了
