### ISSUE TITLE
[Bug]: back2top 无法关闭

### ISSUE THREAD

**Issue by ghost** [valor-x/hexo-theme-solitude#212]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Mac/Linux

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

现有的 back2top 是直接居中的，且使用的 logo 就是使用的 pwa 定义的图标。
目前是没办法关闭 back2top 的，没找到选项，是否开启、logo 选项、位置。

**Comment by efuo** [comment]
你是想关掉这个按钮吗
