### ISSUE TITLE
[Feature]: 建议新增 back2top 开关按钮

### ISSUE THREAD

**Issue by son-g0ku** [valor-x/hexo-theme-solitude#213]
### 功能简介

增加 back2top 按钮的选项

### 问题描述

现有的 back2top 是直接居中的，且使用的 logo 就是使用的 pwa 定义的图标。
目前是没办法关闭 back2top 的，没找到选项，是否开启、logo 选项、位置。

### 实现效果

config 中增加对 back2top 按钮的开关选项，支持图片替换而不是默认 favicon；
建议增加对位置的选项。

### 你想到的可行的替代方案

NULL

### 其他内容

NULL

**Comment by efuo** [comment]
> 支持图片替换而不是默认 favicon

这一段是什么意思

**Comment by efuo** [comment]
目前是添加了back_top开关

**Comment by efuo** [comment]
> > 支持图片替换而不是默认 favicon
> 
> 这一段是什么意思

那个不是favicon，是一个icon

**Comment by efuo** [comment]
想要自定义需要自己去改图标库，主题图标支持全自定义的

**Comment by son-g0ku** [comment]
> 想要自定义需要自己去改图标库，主题图标支持全自定义的

<img width="1546" alt="image" src="https://github.com/valor-x/hexo-theme-solitude/assets/152959149/57ff798e-ba19-475c-adce-d71ef9b4d3d4">

其实我想说的是这个位置的 back2top 想要关闭。

**Comment by efuo** [comment]
你为什么截图说明
