### ISSUE TITLE
[Bug]: avatar 超出边界

### ISSUE THREAD

**Issue by son-g0ku** [valor-x/hexo-theme-solitude#216]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Mac/Linux

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

在 card.author.img 设置中使用了 .webp 的图片作为 avatar，然后就会出现下图的问题，图像超过了圆形的边界。

<img width="314" alt="image" src="https://github.com/valor-x/hexo-theme-solitude/assets/152959149/8fa1d0ca-3446-4fcb-8712-81386a3f6ae1">

**Comment by son-g0ku** [comment]
PS: 图片链接 https://pichosting-d4u.pages.dev/assets/solitude/avatar.webp

**Comment by efuo** [comment]
不要传不规则图片或者长方形的

**Comment by efuo** [comment]
<img width="201" alt="image" src="https://github.com/valor-x/hexo-theme-solitude/assets/74389842/9855a9ca-7deb-425e-bf80-ba927c56bb69">
