### ISSUE TITLE
[Feature]: 增加评论系统的适配

### ISSUE THREAD

**Issue by son-g0ku** [valor-x/hexo-theme-solitude#218]
### 功能简介

增加评论系统的适配

### 问题描述

增加对 Artalk 和 Cusdis 评论的适配

### 实现效果

增加对 Artalk 和 Cusdis 评论的适配

**Comment by efuo** [comment]
有时间再看吧

**Comment by efuo** [comment]
Cusdis 效果不好
增加了 Artalk
支持热评、最新评论、热评
