### ISSUE TITLE
[Bug]: tlink 在线工具配置出现样式错误

### ISSUE THREAD

**Issue by 572192274** [valor-x/hexo-theme-solitude#229]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

[Bug]: 评论功能按照文档设置后，发表评论页面没有评论添加。利用51la统计数据，那个官网的sdk代码放置在主题的哪个地方，试了很久都没有生效

**Comment by efuo** [comment]
详细信息提供一下

**Comment by 572192274** [comment]
这个在线工具页面会出现问题
![图片](https://github.com/valor-x/hexo-theme-solitude/assets/41637256/87789f47-04bd-4552-9268-b90d8cea35d2)

**Comment by 572192274** [comment]
> 详细信息提供一下

在线工具页面构建后，按照文档格式书写yaml，会出现问题
![图片](https://github.com/valor-x/hexo-theme-solitude/assets/41637256/a5c01b3e-84f1-4c7e-9212-56e2631be8a2)

**Comment by efuo** [comment]
你把tlink.yaml 放出来

**Comment by 572192274** [comment]
> 你把tlink.yaml 放出来

`links:
  - class_name: AI工具
    descr: 推荐的AI工具
    link_list:
      - name: 文心一言
        avatar: /img/tlink/wenxinyiyan.jpg
        descr: 类ChatGPT
        link: https://yiyan.baidu.com/
      - name: 代码转换
        avatar: /img/tlink/code.jpg
        descr: 不同计算机语言代码转换
        link: https://aicodeconvert.com/
  - class_name: 简历模板
    descr: 好用的简历模板
    link_list:
      - name: 超级简历
        avatar: /img/tlink/chaojijianli.jpg
        descr: 推荐简历一键下载
        link: https://www.wondercv.com
      - name: 乔布简历
        avatar: /img/tlink/qiaobujianli.jpg
        descr: 付费简历生成
        link: https://cv.qiaobutang.com/
  - class_name: 图标
    descr: 好用的图标
    link_list:
      - name: iconfont图标库
        avatar: /img/tlink/iconfont.jpg
        descr: 免费下载图标
        link: https://www.wondercv.com`

**Comment by 572192274** [comment]
> 你把tlink.yaml 放出来

links:
  - class_name: AI工具
    descr: 推荐的AI工具
    link_list:
      - name: 文心一言
        avatar: /img/tlink/wenxinyiyan.jpg
        descr: 类ChatGPT
        link: https://yiyan.baidu.com/
      - name: 代码转换
        avatar: /img/tlink/code.jpg
        descr: 不同计算机语言代码转换
        link: https://aicodeconvert.com/
  - class_name: 简历模板
    descr: 好用的简历模板
    link_list:
      - name: 超级简历
        avatar: /img/tlink/chaojijianli.jpg
        descr: 推荐简历一键下载
        link: https://www.wondercv.com
      - name: 乔布简历
        avatar: /img/tlink/qiaobujianli.jpg
        descr: 付费简历生成
        link: https://cv.qiaobutang.com/
  - class_name: 图标
    descr: 好用的图标
    link_list:
      - name: iconfont图标库
        avatar: /img/tlink/iconfont.jpg
        descr: 免费下载图标
        link: https://www.wondercv.com

**Comment by 572192274** [comment]
> 你把tlink.yaml 放出来

![图片](https://github.com/valor-x/hexo-theme-solitude/assets/41637256/0469e5a8-63b0-44da-9d44-48c9337fd6be)

**Comment by efuo** [comment]
<img width="1440" alt="image" src="https://github.com/valor-x/hexo-theme-solitude/assets/74389842/876b9438-e3fd-4c41-a291-6fc2927f0ccc">

没啥问题，你把 tlink/index.md 发出来看下

**Comment by efuo** [comment]
issue名字帮你改了，有什么不会的可以开Discussions问，这不是bug

**Comment by 572192274** [comment]
> <img alt="image" width="1440" src="https://private-user-images.githubusercontent.com/74389842/322255824-876b9438-e3fd-4c41-a291-6fc2927f0ccc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwOTUwMjEsIm5iZiI6MTcxMzA5NDcyMSwicGF0aCI6Ii83NDM4OTg0Mi8zMjIyNTU4MjQtODc2Yjk0MzgtZTNmZC00YzQxLWEyOTEtNmZjMjkyN2YwY2NjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDExMzg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmZTBhMDc5ZGVjNjNiYWZiZjMyNWE3NTg0Yzc0NzkwNGM0ZTc3OTgxYjdlNGU3MWE2MjkxOTUyZmM4MTE5ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Leobb3UbxxjI6esR9rMWn2JfWXGhA9DtfRTV2NpkrBA">
> 
> 没啥问题，你把 tlink/index.md 发出来看下

![图片](https://github.com/valor-x/hexo-theme-solitude/assets/41637256/888960d1-b7ca-4be5-bc97-64e88dece13d)

**Comment by efuo** [comment]
<img width="1443" alt="image" src="https://github.com/valor-x/hexo-theme-solitude/assets/74389842/a467ad01-61b1-4556-9310-90d7ad6d914a">

不知bug，这有点迷

**Comment by efuo** [comment]
哦哦，我知道了，你没有启用友情链接，样式并没有生效，友情链接和在线工具样式是公用的。

**Comment by efuo** [comment]
等会交一个小版本修复一下，感谢

**Comment by efuo** [comment]
已修，扩展了可使用的样式，与友情链接配置相同

**Comment by efuo** [comment]
还有你之前提到的 51.la 使用方法，刚写了篇文章介绍 [Hexo：为你的网站添加 51.la 统计](https://www.efu.me/posts/e59bdb81.html)
