### ISSUE TITLE
[Feature]:  新增 site.icon 的功能开关

### ISSUE THREAD

**Issue by son-g0ku** [valor-x/hexo-theme-solitude#236]
### 功能简介

新增 site.icon 的功能开关

### 问题描述

目前 site.icon 的选项无论是否注释或者删除 icon 资源的链接都会在 footer 显示。但是这样会显得很突兀，又没有关闭的选项，希望能有一个关闭的选项实现。

### 实现效果

实现 site.icon 配置项目的开关功能，如不填写或者注释 icon: /*.ico 则不显示，如填写则显示。不然的话显得突兀。

**Comment by efuo** [comment]
你的意思是把这个关了吧
<img width="674" alt="image" src="https://github.com/valor-x/hexo-theme-solitude/assets/74389842/6b15d0d2-447a-4579-8d7c-ef45bb7ef1cf">

描述问题代截图，清晰说明需要什么

**Comment by son-g0ku** [comment]
> 你的意思是把这个关了吧 <img alt="image" width="674" src="https://private-user-images.githubusercontent.com/74389842/322281491-6b15d0d2-447a-4579-8d7c-ef45bb7ef1cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxMDY1OTcsIm5iZiI6MTcxMzEwNjI5NywicGF0aCI6Ii83NDM4OTg0Mi8zMjIyODE0OTEtNmIxNWQwZDItNDQ3YS00NTc5LThkN2MtZWY0NWJiN2VmMWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDE0NTEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkYjk5Y2M4Y2E4MTY4YWU0OTllMTZiZjI0ODJlODQ0NzA0OWZlMGJjZmU0MmIzNjVjZDMzYzU3ZTkxNjMyOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GD9MAQ2f0b1WgyQPMOvjzaca5KFVQ9htHohlriBnkjk">
> 
> 描述问题代截图，清晰说明需要什么

是的，希望把这个关了。

**Comment by efuo** [comment]
可以暂时先到 `layout/includes/footer.pug` 中第20行的位置找到：
```jade
 div#footer_mini_logo.nolazyload.footer_mini_logo(title=_p('nav.backtop'), onclick="sco.toTop()")
     img(src=theme.site.icon, alt=_p('nav.backtop'))
```
暂时将其注释，待下个版本添加，希望你升级到1.8.3，文档已经更新
