### ISSUE TITLE
[Bug]: 自定义右键菜单

### ISSUE THREAD

**Issue by guidocn** [valor-x/hexo-theme-solitude#238]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

# 自定义右键菜单 (Custom Right Menu)
right_menu:
  enable: true
![](https://img.guido.cn/pic/recording.gif)
启动了没反应

**Comment by efuo** [comment]
控制台又没有保存

**Comment by efuo** [comment]
控制台有没有报错

**Comment by efuo** [comment]
浏览器控制台

**Comment by guidocn** [comment]
Uncaught TypeError: Cannot read properties of null (reading 'style')
    at window.oncontextmenu (right_menu.js?v=1.8.2:138:29)
window.oncontextmenu @ right_menu.js?v=1.8.2:138

**Comment by efuo** [comment]
ok,马上解决

**Comment by efuo** [comment]
你可以拉下来试试，在dev分之拉下来试试

**Comment by guidocn** [comment]
貌似问题依旧存在

Uncaught TypeError: Cannot read properties of null (reading 'style')
    at window.oncontextmenu (right_menu.js?v=1.8.4:140:29)
window.oncontextmenu @ right_menu.js?v=1.8.4:140

**Comment by efuo** [comment]
再试试

**Comment by guidocn** [comment]
可以可以

**Comment by efuo** [comment]
好的

**Comment by yeminxi** [comment]
ncaught TypeError: Cannot read properties of null (reading 'style')
    at right_menu.js?v=2.1.8:141:49
    at Array.forEach (<anonymous>)
    at window.oncontextmenu (right_menu.js?v=2.1.8:141:28)
hexo 7.3.0
2.1.8 dev 版本
bug再现
![{F0F89D2F-9F7A-40DD-BEA0-76C7B90ECA2C}](https://github.com/user-attachments/assets/a654f030-7284-4a67-b86e-5701dde47bc8)

**Comment by everfu** [comment]
没遇到
<img width="1680" alt="image" src="https://github.com/user-attachments/assets/d58c0877-fe78-4167-b3b0-b9152d10f758">

**Comment by yeminxi** [comment]
> 没遇到 <img alt="image" width="1680" src="https://private-user-images.githubusercontent.com/74389842/387186675-d58c0877-fe78-4167-b3b0-b9152d10f758.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MzMxODAsIm5iZiI6MTczMTkzMjg4MCwicGF0aCI6Ii83NDM4OTg0Mi8zODcxODY2NzUtZDU4YzA4NzctZmU3OC00MTY3LWIzYjAtYjkxNTJkMTBmNzU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDEyMjgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwYjA5MGE5OTA0N2EzMzU3YjM3Mjc1NGEwYWUyYjJkODgzZWU2NzQ3NmMzMGQzMjA3NGYyYThiN2NjZjc3YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LSnCv-Cb6-BNKFB6FyE-sKEY5Sl3s9iwmmtKXYjaSGc">

是因为我在本地部署的原因？

**Comment by everfu** [comment]
我也是本地

**Comment by MskTmi** [comment]
我也碰到了这个问题，经过尝试可能是没有开启搜索以及aplayer导致
第一次报错：
![0](https://github.com/user-attachments/assets/e8c337e9-1c8b-43ac-b2de-f5bc6200ca8c)
配置搜索功能后，控制台报错变为了：
![1](https://github.com/user-attachments/assets/7d920531-b62c-4831-b6e0-b63af67819fa)
在删除第二张图片的报错代码后，自定义右键菜单能够正常弹出
