### ISSUE TITLE
[Feature]: moments 鱼塘 ，增加 api 返回json 案例

### ISSUE THREAD

**Issue by jiangfeng0103** [valor-x/hexo-theme-solitude#242]
### 功能简介

提供鱼塘 api 返回的demo json数据

### 问题描述

提供案例数据，每个博主可以根据自己的实际需要构建自己的api
现在没有可供参考的api

### 实现效果

提供案例数据，每个博主可以根据自己的实际需要构建自己的api

### 你想到的可行的替代方案

提供一个 json demo

**Comment by efuo** [comment]
鱼塘不是json提供的数据，另外一个[项目])(https://fcircle-doc.js.cool/#/)

**Comment by jiangfeng0103** [comment]
这个打不开

**Comment by efuo** [comment]
项目地址：https://github.com/Rock-Candy-Tea/hexo-circle-of-friends
试试这个：https://hiltay.github.io/hexo-circle-of-friends-doc/#/

**Comment by jiangfeng0103** [comment]
谢谢，已经配置成功了

另外，我是做一个和moment类似的page，用同样的css，但样式一直不对，如下图
![2024-04-19_131848](https://github.com/valor-x/hexo-theme-solitude/assets/12807989/3e9920c0-c6ac-401f-9c75-08eb36b7fc20)
鱼塘的 css 是动态加载的吗？

**Comment by efuo** [comment]
> 谢谢，已经配置成功了
> 
> 另外，我是做一个和moment类似的page，用同样的css，但样式一直不对，如下图 ![2024-04-19_131848](https://private-user-images.githubusercontent.com/12807989/323840728-3e9920c0-c6ac-401f-9c75-08eb36b7fc20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MDQ2ODYsIm5iZiI6MTcxMzUwNDM4NiwicGF0aCI6Ii8xMjgwNzk4OS8zMjM4NDA3MjgtM2U5OTIwYzAtYzZhYy00MDFmLTljNzUtMDhlYjM2YjdmYzIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA1MjYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiMjIxMmNkN2U0M2E2OTA3MWFhZDYzZWEwOGRlMTFlMmY0ZThiYmFhYWFmNmZhODZmODUyNjNiOGI0NmQ3NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4BcXHSCATiUV-w6XU9DPeOzu2nqBFxRw3EVDgx_TKgc) 鱼塘的 css 是动态加载的吗？

好的，不过鱼塘的后端js很久没改了，我找个时间重新发一下

**Comment by efuo** [comment]
你好，可查看我的文章进行自定义，请您更新到最新版本主题[Hexo：添加友链鱼塘](https://www.efu.me/posts/d3883050.html)

**Comment by efuo** [comment]
重新更新了一下，之前的友链鱼塘的文件失效了
