### ISSUE TITLE
[Bug]: 音乐页面包括胶囊音乐跳转到其他页面或者文章后重新刷新了

### ISSUE THREAD

**Issue by hulebaji** [valor-x/hexo-theme-solitude#260]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

音乐页面包括胶囊音乐跳转到其他页面或者文章后自动的重新刷新，在efu的网站中也是同样的问题

**Comment by efuo** [comment]
我的站是改过的，没有参考价值

**Comment by efuo** [comment]
没有问题，除非是自己加js破坏了pjax

**Comment by efuo** [comment]
注意检查自定义js是否破坏了pjax

**Comment by Oilan94** [comment]
遇到同样的问题，没有修改其他文件，只安装了gulp。
