### ISSUE TITLE
[Feature]: 文章页面增加一个随机广告页面，通过_data下的 yaml 配置

### ISSUE THREAD

**Issue by jiangfeng0103** [valor-x/hexo-theme-solitude#266]
### 功能简介

增加一个随机广告

### 问题描述

大家可以通过淘宝联盟，京东联盟，阿里云等获取自己的推广链接，当用户浏览时，随机获取一个广告展示，可以增加收入

### 实现效果

![微信图片_20240501170759](https://github.com/valor-x/hexo-theme-solitude/assets/12807989/b56397f4-3d98-4a30-b568-3229f38b2f31)

**Comment by jiangfeng0103** [comment]
文章底部，文章右侧，随机自定义广告，一张图片，点图片跳转到广告

**Comment by isYangs** [comment]
目前有其他的主题适配这些吗，可以描述的在具体一些，是要在加上这三个广告联盟

**Comment by jiangfeng0103** [comment]
其他的主题没有看到过，只是给大家增加一个变现通道

广告联盟不用关注是哪个平台的，每个广告联盟都会提供一张图片，一个链接， 把图片和链接放到 _data 下面的yaml文件里，具体商品自己登录广告联盟选择商品就可以
目前广告联盟有很多， 淘宝，京东，拼多多，携程等都有

咱们可以搞个简单的通过yaml的方式，这样简单

博客园的 https://www.cnblogs.com/
类似云计算的长年都是有效的，阿里云，腾讯云，这个连个推广收益挺高的
阿里云大使注册 https://www.aliyun.com/ntms/yunparter/personal-center.html
腾讯云大使注册 https://cloud.tencent.com/act/partner/cps
![image](https://github.com/valor-x/hexo-theme-solitude/assets/12807989/f47f86a0-7fd5-4ed9-af4d-8420e3fd1fa6)

淘宝联盟  https://pub.alimama.com/
京东联盟 https://union.jd.com/index

**Comment by jiangfeng0103** [comment]
今日头条 样例  https://www.toutiao.com/
![image](https://github.com/valor-x/hexo-theme-solitude/assets/12807989/4b7f4bbf-cc5e-4a3b-8c5d-03961302e3da)
博客园 样例  https://www.cnblogs.com/
![image](https://github.com/valor-x/hexo-theme-solitude/assets/12807989/c3e3d4dc-44df-4fbb-8fc1-0d84235137ad)

如果_data的yaml是个list广告就可以随机显示一个

**Comment by jiangfeng0103** [comment]
https://www.smm.cn/
这个网站的右侧广告样式也挺好的

**Comment by efuo** [comment]
如果仅是侧边栏的话，可以自行定义添加，可以通过我的博文：https://www.efu.me/posts/9f8c7de5.html
了解如何使用

**Comment by isYangs** [comment]
首先你得想法是好的，但是因为广告的特殊性。

通过以下几点原因综合考虑主题大概率不会支持：

1. 每新增一个广告联盟都要去申请对应的key或id，增加了测试成本。
2. 广告功能并不是每个用户都会使用的，增加了维护成本。
3. 过多的广告只会影响主题整体的美观和使用体验。 

且每个用户使用的广告联盟都有所不同很难做到顾全，我的建议是有能力可以自行修改或按照 @efuo 所说的在侧边栏自定义广告
