### ISSUE TITLE
能不能将模板的yml打包 节省一些喜欢但是又没时间配置这么多细节的朋友

### ISSUE THREAD

**Issue by Elevzent** [valor-x/hexo-theme-solitude#275]
### 功能简介

能不能将模板的yml打包 节省一些喜欢但是又没时间配置这么多细节的朋友的时间

### 问题描述

建议简化配置项（模板打包），方便快速建blog，将精力花费在创作(内容）上

### 实现效果

简化配置项，方便快速建blog，将精力花费在创作(内容）上

**Comment by efuo** [comment]
建议通过文档进行配置，如果有些地方看不懂可以参考 solitude.js.org 的仓库 https://github.com/efuo/solitude.js.org
