### ISSUE TITLE
[Bug]: 中控台异常

### ISSUE THREAD

**Issue by icemyst** [valor-x/hexo-theme-solitude#276]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

主域名和js.org我都看过，都有问题，要调整

### 终端日志 📒

<img width="1265" alt="屏幕截图 2024-05-08 235522" src="https://github.com/valor-x/hexo-theme-solitude/assets/68908911/63399ec7-c37e-4117-88f3-64c0708c33ad">

**Comment by efuo** [comment]
描述下问题

**Comment by efuo** [comment]
描述问题：中控台高度异常，遮挡右侧关闭按钮
