### ISSUE TITLE
[Bug]: btn按钮在折叠块 fold中显示异常

### ISSUE THREAD

**Issue by MGHYGitHub** [valor-x/hexo-theme-solitude#289]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

按钮btn在表格之中,在折叠块下会显示异常
单独在折叠块中显示正常

![7ab8bd381a09038b5129e15aef008d8](https://github.com/valor-x/hexo-theme-solitude/assets/113328471/72050756-52e9-4bf1-8d77-b6dc891f84d8)
![b1e87d0e89e76b7fd1b7ba6aca80111](https://github.com/valor-x/hexo-theme-solitude/assets/113328471/064baf3d-94cc-4eea-9090-f50f7713ccc0)

**Comment by everfu** [comment]
表格直接渲染成字符串了大概
@yife68

**Comment by everfu** [comment]
这应该跟使用的渲染器有关
